<a href="https://colab.research.google.com/github/u4utkam/test/blob/master/4_Numpy_4_Dec24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst = [10, 20, 30, 40, 50]
b = lst
b[0] = 100
print(lst)

[100, 20, 30, 40, 50]


In [ ]:
a = [10, 20, 30, 40, 50]
b = a[:] # slicing
b[0] = 100
print(a)
print(b)

[10, 20, 30, 40, 50]
[100, 20, 30, 40, 50]


In [ ]:
a = np.arange(4)
b = a.reshape(2, 2)

a[0] = 100
b

array([[100,   1],
       [  2,   3]])

In [ ]:
a = np.arange(4)
c = a + 1
c[0] = 100
print(a)
print(c)

[0 1 2 3]
[100   2   3   4]


In [ ]:
np.shares_memory(a, c)

False

In [ ]:
a = np.arange(4)
b = a.reshape(2, 2)

a[0] = 100
np.shares_memory(a, b)

True

In [ ]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]
b[0] = 10
print(b)


[10  1  2  3  4  5]


In [ ]:
np.shares_memory(a, b)

False

In [ ]:
a = np.arange(10)
a_shallow_copy = a.view()
np.shares_memory(a, a_shallow_copy)

True

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_shallow_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_deep_copy = a.copy()
a_deep_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.shares_memory(a, a_deep_copy)

False

In [ ]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
np.split(a, 4)

ValueError: array split does not result in an equal division

In [ ]:
np.split(a, [3, 5, 6])

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [ ]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.split(a, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(a, np.array([3]))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)
np.vstack([a, b, c])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.hstack([a, a])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
np.concatenate((a, b), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [ ]:
a = np.array([[0, 10, 20, 30]])
a

array([[ 0, 10, 20, 30]])

In [ ]:
np.vstack((a, a, a)).T


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.tile(np.arange(0, 3), (4, 1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
c = np.array([0, 1, 2])
a + c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.array([[[[1, 2], [1, 2]], [[1, 2], [1, 2]]]])